# Lesson 13 - Overfitting
Austin Derrow-Pinion

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
train = np.load('./Data/notMNIST_train_100.npz')
test = np.load('./Data/notMNIST_test_100.npz')
print("Train keys: ", train.keys())
print("Test keys:  ", test.keys())

Train keys:  ['train_images', 'train_labels']
Test keys:   ['test_images', 'test_labels']


In [4]:
train_images = train['train_images']
test_images = test['test_images']

train_labels = train['train_labels']
test_labels = test['test_labels']

print("Train images shape: ", train_images.shape)
print("Train labels shape: ", train_labels.shape)

print("\nTest images shape: ", test_images.shape)
print("Test labels shape: ", test_labels.shape)

Train images shape:  (100, 28, 28)
Train labels shape:  (100,)

Test images shape:  (100, 28, 28)
Test labels shape:  (100,)


In [7]:
print("train_labels:\n", train_labels)
print("test_labesl:\n", test_labels)

train_labels:
 [0 9 2 7 3 8 6 6 3 9 0 1 8 3 6 9 6 8 9 3 1 5 9 3 4 4 3 3 6 8 2 6 3 3 3 5 6
 3 9 8 6 9 0 0 6 9 7 8 6 7 2 4 9 5 9 0 1 9 7 4 6 4 2 9 7 9 9 3 0 8 3 6 7 4
 2 1 3 6 3 3 3 4 3 8 8 0 5 8 1 6 8 4 2 2 7 0 3 8 4 3]
test_labesl:
 [2 5 6 9 3 9 1 4 4 7 6 2 9 5 9 6 1 6 0 4 2 3 2 5 3 0 8 3 6 7 5 1 2 5 2 0 9
 3 2 5 1 8 6 5 0 0 5 0 9 9 6 3 1 5 6 1 2 6 1 5 3 5 4 7 8 0 8 0 5 9 8 9 2 3
 3 9 2 9 2 3 4 7 9 5 7 0 9 8 5 2 4 8 1 5 8 4 3 4 4 7]


In [8]:
# prepare input data
x_test = test_images.reshape(100, 28*28).astype(np.float32)

x_train = train_images.reshape(100, 28*28)
print("x_train shape: ", x_train.shape)
x_train[0][235:240]

x_train shape:  (100, 784)


array([-0.5       , -0.5       , -0.5       , -0.49215686, -0.5       ], dtype=float32)

In [9]:
# prepare output data
y_test = pd.get_dummies(test_labels).values.astype(np.float32)

y_train = pd.get_dummies(train_labels).values.astype(np.float32)
print("y_train shape: ", y_train.shape)
y_train[0:3]

y_train shape:  (100, 10)


array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [91]:
# Tensorflow computation graph

# y = softmax(x * w + b)
x = tf.constant(x_train, dtype='float32', shape=[100, 784])
y = tf.constant(y_train, dtype='float32', shape=[100, 10])

w = tf.Variable(tf.truncated_normal([784, 10], stddev=0.001))
b = tf.Variable(tf.truncated_normal([1, 10], stddev=0.001))

# output of function
y_pred = tf.nn.softmax(tf.matmul(x, w) + b)

# test predictions
x_test_tf = tf.constant(x_test, dtype='float32', shape=[100, 784])
y_pred_test = tf.nn.softmax(tf.matmul(x_test_tf, w) + b)

# error loss function
MSE = tf.reduce_mean(tf.square(y_pred - y))

# define optimizer
# optimizer = tf.train.AdamOptimizer(learning_rate=0.01,
#                                    epsilon=1.0,
#                                   beta1=0.8,
#                                   beta2=0.9).minimize(MSE)
optimizer = tf.train.AdamOptimizer(learning_rate=0.01,
                                   epsilon=0.1,
                                  beta1=0.8,
                                  beta2=0.9).minimize(MSE)

init = tf.initialize_all_variables()

In [92]:
sess = tf.Session()
sess.run(init)

In [93]:
MAXSTEPS = 30000
for step in range(MAXSTEPS + 1):
    (_, mse, w0, b0) = sess.run([optimizer, MSE, w, b])
    if (step % 1000) == 0:
        print('step = %-5d MSE = %-10f' % (step, mse))
print('done!')

step = 0     MSE = 0.090026  
step = 1000  MSE = 0.009524  
step = 2000  MSE = 0.004368  
step = 3000  MSE = 0.003347  
step = 4000  MSE = 0.002942  
step = 5000  MSE = 0.002147  
step = 6000  MSE = 0.001671  
step = 7000  MSE = 0.001557  
step = 8000  MSE = 0.001489  
step = 9000  MSE = 0.001442  
step = 10000 MSE = 0.001407  
step = 11000 MSE = 0.001380  
step = 12000 MSE = 0.001358  
step = 13000 MSE = 0.001340  
step = 14000 MSE = 0.001326  
step = 15000 MSE = 0.001313  
step = 16000 MSE = 0.001302  
step = 17000 MSE = 0.001293  
step = 18000 MSE = 0.001285  
step = 19000 MSE = 0.001278  
step = 20000 MSE = 0.001272  
step = 21000 MSE = 0.001266  
step = 22000 MSE = 0.001261  
step = 23000 MSE = 0.001256  
step = 24000 MSE = 0.001252  
step = 25000 MSE = 0.001248  
step = 26000 MSE = 0.001245  
step = 27000 MSE = 0.001242  
step = 28000 MSE = 0.001239  
step = 29000 MSE = 0.001236  
step = 30000 MSE = 0.001233  
done!


In [94]:
# make predictions
predictions = sess.run(y_pred)
predictions[0:1]

array([[  9.69292819e-01,   1.01417466e-03,   1.62245502e-04,
          1.41731033e-03,   4.73107677e-04,   4.55135538e-04,
          4.95199719e-03,   1.53658586e-02,   7.29440828e-04,
          6.13799598e-03]], dtype=float32)

In [95]:
# check mean square error
mse = ((y_train - predictions) ** 2).mean()
rmse = np.sqrt(mse)
print('MSE = ', mse)
print('RMSE = ', rmse)
print('output\'s standard deviation = ', y_train.std())
print('difference between RMSE of model and std of LogRatios: ', (y_train.std() - rmse))

MSE =  0.00123347
RMSE =  0.0351208
output's standard deviation =  0.3
difference between RMSE of model and std of LogRatios:  0.264879


In [96]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

In [97]:
accuracy = accuracy_score(np.argmax(y_train, axis=1), np.argmax(predictions, axis=1))

print("TensorFlow's training accuracy: ", accuracy)

TensorFlow's training accuracy:  0.99


In [98]:
predictions_test = sess.run(y_pred_test)

# check mean square error
mse_test = mean_squared_error(y_test, predictions_test)

print("TensorFlow's MSE: ", mse_test)

TensorFlow's MSE:  0.0404235


In [99]:
accuracy_test = accuracy_score(np.argmax(y_test, axis=1), np.argmax(predictions_test, axis=1))

print("TensorFlow's accuracy: ", accuracy_test)

TensorFlow's accuracy:  0.71
